[package]
name = "definitions-manager-lib"
edition = "2021"
rust-version = "1.80.1"
version = "0.1.0-SNAPSHOT"
license = "MIT"
[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
serde_json = "1.0.127"
jsonschema = "0.18.1"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread", "time"] }
demonstrate = { version = "0.4.5"}
hamcrest2 = "0.3.0"
