[workspace]
members = [
    "definitions-manager-lib",
    "definitions-manager-json",
    "definitions-manager-toml",
    "definitions-cli",
    "rc-web"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80.1"
version = "0.1.0-SNAPSHOT"
license = "MIT"

