[package]
name = "rc-web"
edition = "2021"
rust-version = "1.80.1"
version = "0.1.0-SNAPSHOT"
license = "MIT"
[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.210", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
serde_json = "1.0.128"
validator = { version = "0.18.1", features = ["derive"] }
definitions-manager-lib = { path = "../definitions-manager-lib" }
[dev-dependencies]
actix-rt = "2.10.0"
[profile.dev]
split-debuginfo = "unpacked"
