version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: daksha_rc
      POSTGRES_PASSWORD: daksha_rc
      POSTGRES_DB: daksha_rc
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U daksha_rc" ]
          interval: 30s
          timeout: 10s
          retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGPASSFILE: /pgadmin4/pgpassfile
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./db/pgadminservers.json:/pgadmin4/servers.json
      - ./db/pgpassfile:/pgadmin4/pgpassfile
volumes:
  db-data: