[package]
name = "definitions-cli"
edition = "2021"
rust-version = "1.80.1"
version = "0.1.0-SNAPSHOT"
license = "MIT"
[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
