name: Build Basic Image - Simple

on:
  push:
    branches:
      - "#36_Deploy_to_UTHO_k8s"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the basic image (e.g., v0.0.2)"
        required: true
        type: string
        default: "v0.0.2"

jobs:
  build-basic:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Install cargo-make
        run: cargo install cargo-make

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push basic image
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG=${{ github.event.inputs.tag }}
          else
            # Use git tag or fallback to branch-based tag for push events
            TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "branch-$(date +%Y%m%d-%H%M%S)")
          fi
          TAG=$TAG cargo make build-and-push-basic-with-tag

      - name: Verify build
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG=${{ github.event.inputs.tag }}
          else
            TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "branch-$(date +%Y%m%d-%H%M%S)")
          fi
          echo "✅ Successfully built and pushed basic image with tag: $TAG"
          podman images | grep rc-basic || true
